config/routes.rb
CycomTournament::Application.routes.draw do |map|
  resources :rounds

  resources :trees do
    get :generate, :on => :member
  end

  resources :groups, :only => [ :show ] do
    get :generate_games, :on => :member
  end
  resources :rankings do
    get :generate_games, :on => :member
  end
  resources :subscriptions, :only => [ :create, :destroy ]
  resources :tournaments do
    get :start, :on => :member
  end
  resources :events
  resources :memberships, :only => [ :create, :destroy ]
  resources :teams
  resources :posts
  resources :users
  resources :branches
  
  match 'login' => "sessions#create", :as => :login
  match 'logout' => "sessions#destroy", :as => :logout

  root :to => "posts#index"

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  validates_presence_of :name, :abbreviation
  validates_uniqueness_of :name, :abbreviation
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  respond_to :html
  
  before_filter :check_admin, :except => [ :index, :show ]
  
  def index
    @branches = Branch.all

    respond_with(@branches)
  end

  def show
    @branch = Branch.find(params[:id])

    respond_with(@branch)
  end

  def new
    @branch = Branch.new

    respond_with(@branch)
  end

  def edit
    @branch = Branch.find(params[:id])
  end

  def create
    @branch = Branch.create(params[:branch])

    respond_with(@branch)
  end

  def update
    @branch = Branch.find(params[:id])
    @branch.update_attributes(params[:branch])
    
    respond_with(@branch)
  end

  def destroy
    @branch = Branch.find(params[:id])
    @branch.destroy

    respond_with(:location => branches_path)
  end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.erb
<% form_for(@branch) do |f| %>
  <%= render "shared/error_messages", :target => @branch %>
  <%= f.text_field :name %>
  <%= f.text_field :abbreviation %>
  <%= f.text_area :description %>
  <%= f.submit @branch.new_record? ? t("validate.new") : t("validate.edit") %>
<% end %>

app/views/branches/edit.html.erb
<%= h2 t('branch.edit') %>

<%= render 'form' %>

app/views/branches/index.html.erb
<%= h2 t("branch.index") %>

<table>
  <tr>
    <th><%= t "activerecord.attributes.branch.name" %></th>
    <th><%= t "activerecord.attributes.branch.abbreviation" %></th>
    <th><%= t "activerecord.attributes.branch.description" %></th>
  </tr>

<% for branch in @branches %>
  <tr>
    <td><%=h branch.name %></td>
    <td><%=h branch.abbreviation %></td>
    <td><%=h branch.description %></td>
    <td><%= link_to t("general.show"), branch %></td>
    <% if admin? -%>
      <td><%= link_to t("general.edit"), edit_branch_path(branch) %></td>
      <td><%= link_to t("general.delete"), branch, :confirm => t("general.confirm"), :method => :delete %></td>
    <% end -%>
  </tr>
<% end %>
</table>

<br />

<%= link_to t("branch.new"), new_branch_path if admin? %>

app/views/branches/new.html.erb
<%= h2 t('branch.new') %>

<%= render 'form' %>

app/views/branches/show.html.erb
<%= h2 @branch.name %>

<p>
  <b><%= t "activerecord.attributes.branch.name" %>:</b>
  <%=h @branch.name %>
</p>

<p>
  <b><%= t "activerecord.attributes.branch.abbreviation" %>:</b>
  <%=h @branch.abbreviation %>
</p>

<p>
  <b><%= t "activerecord.attributes.branch.description" %>:</b>
  <%=h @branch.description %>
</p>