config/routes.rb
CycomTournament::Application.routes.draw do |map|
  resources :rounds

  resources :trees do
    get :generate, :on => :member
  end

  resources :groups, :only => [ :show ] do
    get :generate_games, :on => :member
  end
  resources :rankings do
    get :generate_games, :on => :member
  end
  resources :subscriptions, :only => [ :create, :destroy ]
  resources :tournaments do
    get :start, :on => :member
  end
  resources :events
  resources :memberships, :only => [ :create, :destroy ]
  resources :teams
  resources :posts
  resources :users
  resources :branches
  
  match 'login' => "sessions#create", :as => :login
  match 'logout' => "sessions#destroy", :as => :logout

  root :to => "posts#index"

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :cookies, :class_name => "UserCookie"
    has_many :branches, :through => :memberships
    has_many :teams, :through => :memberships
    #has_many :articles
    #has_many :orders
    has_many :subscriptions, :foreign_key => "participant_id"
    has_many :tournaments, :through => :subscriptions
    
    # Avoid mass assignment
    attr_accessible :first_name, :last_name, :nickname, :email, :password,
    :password_confirmation, :phone, :address, :city, :zip_code, :country,
    :sex, :birthdate

    # Validations
    validates_presence_of :first_name, :last_name, :nickname, :email, :birthdate
    validates_uniqueness_of :nickname, :email
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

    validates_presence_of :password, :if => :should_give_password?
    validates_presence_of :password_confirmation, :if => :should_give_password_confirmation?
    validates_confirmation_of :password

    # Password attribute
    attr_reader :password

    # Assign password attribute and generate random salt and SHA1 digest
    def password=(pass)
      @password = pass
      self.password_salt = [Array.new(10) { rand(256).chr }.join].pack("m").chomp
      self.password_hash = Digest::SHA1.hexdigest(pass + password_salt)
    end

    def password_is?(pass)
      password_hash == Digest::SHA1.hexdigest(pass + password_salt)
    end

    def admin?
      admin
    end

    # Password is mandatory only at account creation
    def should_give_password?
      self.password_hash.nil?
    end

    # Password confirmation is madatory only at account creation 
    # or when password is specified
    def should_give_password_confirmation?
      should_give_password? or !@password.nil?
    end
    
    def self.available_for_tournament(tournament_id)  
      result = []
      users = all

      for user in users
        result << user unless user.tournaments.exists?(tournament_id)
      end

      result
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :check_admin, :except => [:index, :show, :new, :create]
  respond_to :html
  
  def index
    @users = User.all
    
    respond_with(@users)
  end

  def show
    @user = User.find(params[:id])
    @branches = Membership.team_branches(@user.id)
    #@orders = @user.orders

    respond_with(@user)
  end

  def new
    @user = User.new

    respond_with(@user)
  end

  def edit
    @user = User.find(params[:id])
    @user.password_confirmation = @user.password
  end

  def create
    @user = User.new(params[:user])
    if User.all.size == 0
      @user.admin = 1
    end
    session[:user_id] = @user.id if @user.save
    
    respond_with(@user)
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])

    respond_with(@user)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_with(:location => users_path)
  end
  
  #def manage_admin
  #  @users = User.find(:all, :conditions => { :admin => 1 })
  #end
  
  #def remove_admin
  #  @user = User.find(params[:id])
  #  @user.update_attribute(:admin, false)
  #  redirect_to :action => "manage_admin"
  #end
  
  #def add_admin
  #  @users = User.find(:all, :conditions => { :admin => 0 })
  #end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render "shared/error_messages", :target => @user %>
  <%= f.text_field :first_name %>
  <%= f.text_field :last_name %>
  <%= f.text_field :nickname %>
  <%= f.text_field :email %>
  <%= f.password_field :password %>
  <%= f.password_field :password_confirmation %>
  <%= f.text_field :phone %>
  <%= f.text_field :address %>
  <%= f.text_field :city %>
  <%= f.text_field :zip_code %>
  <%= f.text_field :country %>
  <%= f.select :sex, [['Homme', 'M'], ['Femme', 'F']], :class => 'long' %>
  <%= f.date_select :birthdate,
      :start_year => 100.years.ago.year, :end_year => Time.now.year,
      :default => 20.years.ago, :order => [:day, :month, :year] %>
<% if false %>
  <% if admin? -%>
	<%= f.check_box :admin %>
  <% end -%>
<% end %>
  <%= f.submit @user.new_record? ? t("validate.new") : t("validate.edit") %>
<% end -%>

app/views/users/edit.html.erb
<%= h2 t('user.edit') %>

<%= render 'form' %>

app/views/users/index.html.erb
<% if false %>
<% action_box do -%>
	<% if !logged_in?%>
		<li><%= link_to t("user.new"), { :controller => :users, :action => :new }, :method => "get" %></li>
	<% end -%>
	<% if admin? -%>
		<li><%= link_to t("admin.manage"),{ :controller => :users, :action => :manage_admin }, :class => "admin" %></li>
	<% end -%>
<% end -%>	
<% end %>

<%= h2 t("user.index") %>

<table>
  <tr>
    <th id="userNickname"><%= t "activerecord.attributes.user.nickname" %></th>
    <th id="userFirstName"><%= t "activerecord.attributes.user.first_name" %></th>
    <th id="userLastName"><%= t "activerecord.attributes.user.last_name" %><th>
  </tr>
<% for user in @users %>
  <tr>
    <td><%= user.nickname %></td>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= link_to t("general.show"), user %></td>
    <% if admin? -%>
      <td><%= link_to t("general.edit"), edit_user_path(user) %></td>
      <td><%= link_to t("general.delete"), user, :confirm => t("general.confirm"), :method => :delete %></td>
    <% end -%>
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
<%= h2 t("user.new") %>

<%= render "form" %>

app/views/users/show.html.erb
<% if false %>
<% action_box do -%>
	<% if (@user.id == session[:user_id])%>
		<li><%= link_to t("user.edit"), { :controller => :users, :action => :edit, 
			:user_id => @user.id }, :method => "get" %></li>
	<% end -%>
	<% if admin? -%>
		<li><%= link_to t("admin.manage"),{ :controller => :users, :action => :manage_admin }, :class => "admin" %></li>
		<% if (@user.id != session[:user_id])%>
			<li><%= link_to t("user.edit"), { :controller => :users, :action => :edit, :user_id => @user.id }, :method => "get", :class => "admin"%></li>
		<% end -%>
	<% end -%>
<% end -%>	
<% end %>

<%= h2 "#{t "user.show"} #{@user.nickname}"%>

<ul>
  <li><%= t "activerecord.attributes.user.first_name" %>: <%= @user.first_name %>
  <li><%= t "activerecord.attributes.user.last_name" %>: <%= @user.last_name %></li>
  <li><%= t "activerecord.attributes.user.email" %>: <%= @user.email %></li>
  <li><%= t "user.age" %>: <%= (Date.today.year - @user.birthdate.year) - ((Date.today.yday < @user.birthdate.yday) ? 1 : 0) %> ans</li>
</ul>

<%= h2 t("team.name") unless @branches.empty? %>

<% @branches.each_pair do |branch, memberships| -%>
  <h3><%= branch.name %></h3>
  <ul>
  <% memberships.each do |membership| -%>
    <li>
      <%= link_to membership.team.name, team_path(membership.team) %>
      <% if session[:user_id] == @user.id -%>
	(<%= link_to t("team.leave"), membership_path(membership), :method => :delete  %>)
      <% end -%>
    </li>
  <% end -%>
  </ul>
<% end -%>