config/routes.rb
CycomTournament::Application.routes.draw do |map|
  resources :rounds

  resources :trees do
    get :generate, :on => :member
  end

  resources :groups, :only => [ :show ] do
    get :generate_games, :on => :member
  end
  resources :rankings do
    get :generate_games, :on => :member
  end
  resources :subscriptions, :only => [ :create, :destroy ]
  resources :tournaments do
    get :start, :on => :member
  end
  resources :events
  resources :memberships, :only => [ :create, :destroy ]
  resources :teams
  resources :posts
  resources :users
  resources :branches
  
  match 'login' => "sessions#create", :as => :login
  match 'logout' => "sessions#destroy", :as => :logout

  root :to => "posts#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :tournaments

  attr_accessible :name, :address, :description, :starts_at, :ends_at

  validates_presence_of :name, :starts_at, :ends_at
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  respond_to :html
  
  before_filter :check_admin, :except => [ :index, :show ]

  def index
    @events = Event.order("ends_at DESC")

    respond_with(@events)
  end

  def show
    @event = Event.find(params[:id])

    respond_with(@event)
  end

  def new
    @event = Event.new

    respond_with(@event)
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.create(params[:event])

    respond_with(@event)
  end

  def update
    @event = Event.find(params[:id])
    @event.update_attributes(params[:event])
    
    respond_with(@event)
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_with(:location => events_path)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<% form_for(@event) do |f| %>
  <%= render 'shared/error_messages', :target => @event %>

  <%= f.text_field :name %>
  <%= f.text_area :address %>
  <%= f.text_area :description %>
  <%= f.datetime_select :starts_at %>
  <%= f.datetime_select :ends_at %>

  <%= f.submit @event.new_record? ? t("validate.new") : t("validate.edit") %>
<% end %>

app/views/events/edit.html.erb
<%= h2 t('event.edit') %>

<%= render 'form' %>

app/views/events/index.html.erb
<% if false %>
<% action_box do %>
	<% if admin? %>
		<li><%= link_to t("event.new"), new_event_path, :class => "admin" %></li>
	<% end %>
<% end %>
<% end %>

<% @events.each do |event| %>
  <%= h2 event.name %>
  <div>
  	<%= "#{t("event.description")} : #{event.name}" %><br />
	<%= "#{t("event.adress")} : #{event.address}" %><br />
   	<%= "#{t("event.start")} : #{event.starts_at}" %><br />
    <%= "#{t("event.end")} : #{event.ends_at}" %><br />
	<%= link_to t("general.show"), event %>
	<% if admin? %>
		<%= link_to t("general.edit"), edit_event_path(event) %></td>
		<%= link_to t("general.delete"), event, :confirm => t('general.confirm'), :method => :delete %></td>
	<% end %>
  </div>
<% end %>

app/views/events/new.html.erb
<%= h2 t('event.new') %>

<%= render 'form' %>

app/views/events/show.html.erb
<% if false %>
<% action_box do -%>
	<% if admin? -%>
		<li><%= link_to t("event.edit"), edit_event_path(@event),
				:class => "admin" %></li>
		<li><%= link_to t("tournament.add"), { :controller => :tournaments,
    			:action => :new, :event_id => @event.id },
				:class => "admin" %></li>
	<% end -%>
<% end -%>
<% end -%>

<p>
  <b><%= t "activerecord.attributes.event.name" %>:</b>
  <%=h @event.name %>
</p>

<p>
  <b><%= t "activerecord.attributes.event.address" %>:</b>
  <%=h @event.address %>
</p>

<p>
  <b><%= t "activerecord.attributes.event.description" %>:</b>
  <%=h @event.description %>
</p>

<p>
  <b><%= t "activerecord.attributes.event.starts_at" %>:</b>
  <%=h @event.starts_at %>
</p>

<p>
  <b><%= t "activerecord.attributes.event.ends_at" %>:</b>
  <%=h @event.ends_at %>
</p>

<% unless @event.tournaments.empty? %>
  <%= h2 t("tournament.name") %>
  <ul>
  <% @event.tournaments.each do |t| -%>
    <li><%= link_to t.name, t %></li>
  <% end %>
  </ul>
<% end %>