config/routes.rb
CycomTournament::Application.routes.draw do |map|
  resources :rounds

  resources :trees do
    get :generate, :on => :member
  end

  resources :groups, :only => [ :show ] do
    get :generate_games, :on => :member
  end
  resources :rankings do
    get :generate_games, :on => :member
  end
  resources :subscriptions, :only => [ :create, :destroy ]
  resources :tournaments do
    get :start, :on => :member
  end
  resources :events
  resources :memberships, :only => [ :create, :destroy ]
  resources :teams
  resources :posts
  resources :users
  resources :branches
  
  match 'login' => "sessions#create", :as => :login
  match 'logout' => "sessions#destroy", :as => :logout

  root :to => "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, :class_name => "User"
  
  # Avoid mass assignment
  attr_accessible :title, :content, :date

  # Validations
  validates_presence_of :title, :content, :author_id, :date
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html
  
  before_filter :check_admin, :except => [ :index, :show ]
  
  def index
    @posts = Post.order("date DESC")

    respond_with(@posts)
  end

  def show
    @post = Post.find(params[:id])

    respond_with(@post)
  end

  def new
    @post = Post.new

    respond_with(@post)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params[:post])
    @post.author_id = session[:user_id]
    @post.save
    
    respond_with(@post)
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes(params[:post])
    
    respond_with(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_with(:location => posts_path)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% form_for(@post) do |f| %>
  <%= f.error_messages %>
    <%= f.text_field :title %>
    <%= f.text_area :content %>
    <%= f.datetime_select :date %>
    <%= f.submit @post.new_record? ? t("validate.new") : t("validate.edit") %>
<% end %>

app/views/posts/edit.html.erb
<%= h2 t("post.new") %>

<%= render "form" %>

app/views/posts/index.html.erb
<% if false %>
<% action_box do -%>
	<% if admin? -%>
		<li><%= link_to t("post.new"), new_post_path, :class => "admin" %></li>
	<% end -%>
<% end -%>
<% end %>

<% @posts.each do |post| %>
  <%= h2 post.title%>
  <div>
  	<%=h post.content %>
  </div>
  Post by <%= post.author.nickname %> at <%= post.date %>
  <% if admin? %>
  	<%= link_to t("general.edit"), :controller => :posts, :action => :edit, :id => post.id %>
  	<%= link_to t("general.delete"), {:controller => :posts, :action => :destroy, :id => post.id}, :confirm => "Are you sure?", :method => :delete %>
  <% end %>
<% end -%>

app/views/posts/new.html.erb
<%= h2 t("post.new") %>

<%= render "form" %>

app/views/posts/show.html.erb
<p>
  <b>Title:</b>
  <%=h @post.title %>
</p>

<p>
  <b>Content:</b>
  <%=h @post.content %>
</p>

<p>
  <b>Author:</b>
  <%=h @post.author_id %>
</p>

<p>
  <b>Date:</b>
  <%=h @post.date %>
</p>

<% if admin? -%>
	<%= link_to t("general.edit"), edit_post_path(@post) %> |
<% end -%>
<%= link_to t("general.back"), posts_path %>